### ISSUE TITLE
it looks like some files have lost

### ISSUE THREAD

**Issue by demainchen** [lvguofeng/GNN_PPI#1]
when I try to run code in Pycharm,I find there are a few errors here. It looks like this file does not exist in the file you share in GitHub(string.bfs.fold1.json), and I also try to find it in BaiDuNetDist but failed. Related error information I have added in the attachment. Please fix this bug as soon as possible, if so I would be pretty grateful for your help!

**Comment by lvguofeng** [comment]
There is a GNN_DATA.split_dataset function in gnn_data.py, which is used to generate a JSON file for the data partition.  The parameter random_new needs to be set to 'TRUE'. At the same time, set the parameter split_new=‘true’ in the gnn_train.py.
